master_ssh_username       = "master_user"
worker_ssh_username       = "worker_user"
master_private_key_path   = "/home/dimit/.ssh/id_rsa"
worker_private_key_path   = "/home/dimit/.ssh/uop_aws.pem"
master_ip_addresses       = "172.25.191.1"
worker_ip_addresses       = "54.93.57.121"
