master_ssh_username     = "localadmin"
worker_ssh_username     = "ec2-user"
master_private_key_path = "/home/dimit/.ssh/id_rsa"
worker_private_key_path = "/home/dimit/.ssh/uop_aws.pem"
master_ip_address       = "172.25.191.1"
worker_ip_address       = "54.93.57.121"
