master_ssh_username     = "ubuntu"
worker_ssh_username     = "ec2-user"
master_private_key_path = "/home/dimit/.ssh/uop_key"
worker_private_key_path = "/home/dimit/.ssh/uop_aws.pem"
master_ip_address       = "10.1.6.211"
worker_ip_address       = "3.122.59.110"
